### ISSUE TITLE
Feat: make modloader used case insensitive

### ISSUE THREAD

**Issue by RedBrumbler** [Lauriethefish/QuestPatcher#149]
Seems like the modloader field is case sensitive which is pretty counter intuitive, would be nice to see it be made to be case insensitive

**Comment by raineio** [comment]
Initial report (by me): https://discord.com/channels/994470435100033074/994636496512491540/1199393757477478531

**Comment by Lauriethefish** [comment]
Hey it's been a bit.

Right now the modloader field is case sensitive as that's what the qmod schema has it set as (repo for schema is [here](https://github.com/Lauriethefish/QuestPatcher.Qmod)).

If there's still velocity to change this then I suggest opening an issue there. imho it's not really a problem since everybody is used to the case-sensitive nature of the field now, but it can still be changed.
