### ISSUE TITLE
how do i unpatch

### ISSUE THREAD

**Issue by PaxtonPenguin** [Lauriethefish/QuestPatcher#152]
so i tried to patch gorilla tag for custom maps, and accidentally patched beat saber. terrible ui design aside, this made the feet location go to my last stationary boundary, and not to my new ones. so i uninstalled beat saber and restored it, it didn't fix. i deleted the patch folders, it didn't fix. can you help me out here

**Comment by Lauriethefish** [comment]
Hey.
The app is set to patch Beat Saber by default since that's the most common use-case these days.
Uninstalling Beat Saber will unpatch the app, but you have to do it through QuestPatcher or SideQuest, NOT through the home screen on your quest. I also wouldn't recommend restoring an APK, just uninstall it and reinstall the vanilla version.

If you've already uninstalled the app through the home screen, run this ADB command using SideQuest, then reinstall vanilla:
`adb uninstall com.beatgames.beatsaber`

**Comment by PaxtonPenguin** [comment]
i did, it wouldn't uninstall from the quest so i had to uninstall it using
the quest. it would send me to the store, but i couldn't start it (even
though it said launch).

**Comment by Lauriethefish** [comment]
If you uninstalled it via the quest you need to run the command in the previous post from me to fix the problem. You can then reinstall unmodded Beat Saber and work from there.
I'm closing the issue as this is a problem with the Quest software, not QP. You can't uninstall a modded game from inside the Quest and if you do, you need to run the command to fix it.

**Comment by PaxtonPenguin** [comment]
ok
