### ISSUE TITLE
Prebuilt arm binarys for linux

### ISSUE THREAD

**Issue by PokeyManatee4** [Lauriethefish/QuestPatcher#83]
I have a arm linux machine and can't Compile c# can you?

**Comment by Lauriethefish** [comment]
For now this will be closed, since google provides no prebuilt ARM binaries for ADB (the android debug bridge), which QP requires in order to run. There are only unofficial builds right now.

**Comment by PokeyManatee4** [comment]
I have adb arm I just need qp

**Comment by Lauriethefish** [comment]
If you want to make your own build, I am happy to provide compilation instructions.
Unfortunately I won't be providing prebuilt arm binaries until there is official support from ADB, since they wouldn't work properly, and the downloaded ADB versions would be wrong. If you have your own ADB version on path, however, follow these instructions:
- [Install .NET 6.0](https://docs.microsoft.com/en-us/dotnet/core/install/linux).
- Clone the project: `git clone https://github.com/Lauriethefish/QuestPatcher.git`.
- Publish the project: `dotnet publish ./QuestPatcher/QuestPatcher.csproj -r ubuntu-arm64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -c Release --self-contained`.
- Find your executable in: `./QuestPatcher/bin/Release/net6.0/ubuntu-x64/publish/`
@PokeyManatee4.

**Comment by PokeyManatee4** [comment]
I have some I just need qp

**Comment by Lauriethefish** [comment]
I know, what I am suggesting is that you build QP yourself.

**Comment by Jaydenha09** [comment]
@Lauriethefish can you tell me which part of the code I have to change the adb to unoffical arm build?

**Comment by Lauriethefish** [comment]
This would be the line you have to change:
https://github.com/Lauriethefish/QuestPatcher/blob/main/QuestPatcher.Core/Resources/file-downloads.json#L29
You'd also want to remove the link to that file from the app, as otherwise your changes will be automatically overwritten:
https://github.com/Lauriethefish/QuestPatcher/blob/main/QuestPatcher.Core/ExternalFilesDownloader.cs#L105
Either replace it with some dummy URL that will always fail to load, or link the file in your own repository.

**Comment by Jaydenha09** [comment]
ok Thanks for that

**Comment by Jaydenha09** [comment]
@PokeyManatee4 Maybe its too late but I have build it successfully, you need it?
